services:
  server:
    build: packages/server
    restart: always
    depends_on:
      - databaseXp
    environment:
      MYSQL_HOST: databaseXp
      PORT: $SERVER_SERVICE_PORT
    ports:
      - ${SERVER_SERVICE_PORT}:${SERVER_SERVICE_PORT}
    volumes:
      - ./packages/server:/usr/portfolioXP/
      - /usr/portfolioXP/node_modules
    networks:
      - shared-network
    command: /usr/portfolioXP/node_modules/.bin/nodemon -L --exec ts-node ./src/index.ts
  client:
    build: packages/client
    restart: always
    depends_on:
      - server
    environment:
      PORT: $WEB_CLIENT_PORT
    ports:
      - ${WEB_CLIENT_PORT}:${WEB_CLIENT_PORT}
    volumes:
      - ./packages/client:/usr/portfolioXP/
      - /usr/portfolioXP/node_modules
    networks:
      - shared-network
    command: npm run dev
  databaseXp:
    image: mysql
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/portfolioDb/data
    networks:
      - shared-network
networks:
  shared-network:
    driver: bridge
volumes:
  dbdata: