services:
  server:
    build: packages/server
    restart: always
    # depends_on:
    #   - database
    env_file: .env
    environment:
      - PORT=$SERVER_SERVICE_PORT
      # - PG_HOST=database
      # - PG_PORT=5432
      # - PG_USER=$PG_USER
      # - PG_PASS=$PG_PASS 
      # - PG_DB=$PG_DB
      # - JWT_SECRET=$JWT_SECRET
    ports:
      - ${SERVER_SERVICE_PORT}:${SERVER_SERVICE_PORT}
    volumes:
      - ./packages/server:/usr/portfolioXP/
      - /usr/portfolioXP/node_modules
    networks:
      - shared-network
    command: /usr/portfolioXP/node_modules/.bin/nodemon -L --exec ts-node ./src/index.ts
  client:
    build: packages/client
    restart: always
    env_file: .env
    depends_on:
      - server
    environment:
      - PORT=$WEB_CLIENT_PORT
    ports:
      - ${WEB_CLIENT_PORT}:${WEB_CLIENT_PORT}
    volumes:
      - ./packages/client:/usr/portfolioXP/
      - /usr/portfolioXP/node_modules
    networks:
      - shared-network
    command: npm run dev
  # database:
  #   image: postgres
  #   restart: always
  #   env_file: .env
  #   environment:
  #     POSTGRES_USER: $PG_USER 
  #     POSTGRES_PASSWORD: $PG_PASS
  #     POSTGRES_DB: $PG_DB
  #   volumes:
  #      - dbdata:/var/lib/postgresql/data
  #   networks:
  #     - shared-network
networks:
  shared-network:
    driver: bridge
# volumes:
#   dbdata: